package com.example.util

import android.content.Context
import android.content.Intent
import android.graphics.Canvas
import android.graphics.Color
import android.graphics.Paint
import android.graphics.RectF
import android.graphics.Typeface
import android.graphics.pdf.PdfDocument
import android.text.TextPaint
import android.widget.Toast
import androidx.core.content.FileProvider
import com.example.data.model.ProjectBlueprint
import java.io.File
import java.io.FileOutputStream
import java.io.IOException

object PdfExporter {

    private const val PAGE_WIDTH = 595
    private const val PAGE_HEIGHT = 842
    private const val MARGIN_LEFT = 40f
    private const val MARGIN_RIGHT = 555f
    private const val CONTENT_WIDTH = MARGIN_RIGHT - MARGIN_LEFT // 515f
    private const val MARGIN_TOP = 45f
    private const val MARGIN_BOTTOM = 795f

    fun exportToPdf(context: Context, blueprint: ProjectBlueprint) {
        val pdfDocument = PdfDocument()
        val pageInfoBuilder = PdfDocument.PageInfo.Builder(PAGE_WIDTH, PAGE_HEIGHT, 1)

        var pageNumber = 1
        var page = pdfDocument.startPage(PdfDocument.PageInfo.Builder(PAGE_WIDTH, PAGE_HEIGHT, pageNumber).create())
        var canvas = page.canvas
        var currentY = MARGIN_TOP

        // Paints setup
        val titlePaint = TextPaint().apply {
            color = Color.parseColor("#0F172A") // Dark slate
            textSize = 20f
            typeface = Typeface.create(Typeface.DEFAULT, Typeface.BOLD)
            isAntiAlias = true
        }

        val subtitlePaint = TextPaint().apply {
            color = Color.parseColor("#475569")
            textSize = 10f
            typeface = Typeface.create(Typeface.DEFAULT, Typeface.ITALIC)
            isAntiAlias = true
        }

        val sectionTitlePaint = TextPaint().apply {
            color = Color.parseColor("#1E1B4B") // Deep Indigo
            textSize = 13f
            typeface = Typeface.create(Typeface.DEFAULT, Typeface.BOLD)
            isAntiAlias = true
        }

        val bodyPaint = TextPaint().apply {
            color = Color.parseColor("#334155")
            textSize = 9.5f
            typeface = Typeface.create(Typeface.DEFAULT, Typeface.NORMAL)
            isAntiAlias = true
        }

        val boldBodyPaint = TextPaint().apply {
            color = Color.parseColor("#0F172A")
            textSize = 9.5f
            typeface = Typeface.create(Typeface.DEFAULT, Typeface.BOLD)
            isAntiAlias = true
        }

        val codePaint = TextPaint().apply {
            color = Color.parseColor("#0F766E") // Teal
            textSize = 8.5f
            typeface = Typeface.create(Typeface.MONOSPACE, Typeface.NORMAL)
            isAntiAlias = true
        }

        val footerPaint = TextPaint().apply {
            color = Color.parseColor("#94A3B8")
            textSize = 8f
            typeface = Typeface.create(Typeface.DEFAULT, Typeface.NORMAL)
            isAntiAlias = true
        }

        val bgPaint = Paint().apply { isAntiAlias = true }
        val strokePaint = Paint().apply {
            style = Paint.Style.STROKE
            strokeWidth = 1f
            isAntiAlias = true
        }

        fun drawHeaderFooter() {
            // Header line for page > 1
            if (pageNumber > 1) {
                strokePaint.color = Color.parseColor("#E2E8F0")
                canvas.drawLine(MARGIN_LEFT, 35f, MARGIN_RIGHT, 35f, strokePaint)

                footerPaint.textAlign = Paint.Align.LEFT
                canvas.drawText("${blueprint.name} — Architecture Spec v${blueprint.version}", MARGIN_LEFT, 28f, footerPaint)

                footerPaint.textAlign = Paint.Align.RIGHT
                canvas.drawText("AI App Architect", MARGIN_RIGHT, 28f, footerPaint)
            }

            // Footer for all pages
            strokePaint.color = Color.parseColor("#E2E8F0")
            canvas.drawLine(MARGIN_LEFT, MARGIN_BOTTOM + 5f, MARGIN_RIGHT, MARGIN_BOTTOM + 5f, strokePaint)

            footerPaint.textAlign = Paint.Align.LEFT
            canvas.drawText("Confidential & Proprietary — Generated by AI App Architect", MARGIN_LEFT, MARGIN_BOTTOM + 18f, footerPaint)

            footerPaint.textAlign = Paint.Align.RIGHT
            canvas.drawText("Page $pageNumber", MARGIN_RIGHT, MARGIN_BOTTOM + 18f, footerPaint)
        }

        fun checkPageBreak(requiredHeight: Float) {
            if (currentY + requiredHeight > MARGIN_BOTTOM) {
                drawHeaderFooter()
                pdfDocument.finishPage(page)
                pageNumber++
                page = pdfDocument.startPage(PdfDocument.PageInfo.Builder(PAGE_WIDTH, PAGE_HEIGHT, pageNumber).create())
                canvas = page.canvas
                currentY = MARGIN_TOP + 10f
            }
        }

        fun drawWrappedText(
            text: String,
            x: Float,
            maxWidth: Float,
            paint: TextPaint,
            lineSpacing: Float = 13f
        ) {
            val words = text.split(" ")
            var line = ""
            for (word in words) {
                val testLine = if (line.isEmpty()) word else "$line $word"
                if (paint.measureText(testLine) > maxWidth && line.isNotEmpty()) {
                    checkPageBreak(lineSpacing)
                    canvas.drawText(line, x, currentY, paint)
                    currentY += lineSpacing
                    line = word
                } else {
                    line = testLine
                }
            }
            if (line.isNotEmpty()) {
                checkPageBreak(lineSpacing)
                canvas.drawText(line, x, currentY, paint)
                currentY += lineSpacing
            }
        }

        fun drawSectionHeader(title: String) {
            checkPageBreak(35f)
            currentY += 8f

            // Left accent bar
            bgPaint.color = Color.parseColor("#4F46E5")
            bgPaint.style = Paint.Style.FILL
            canvas.drawRect(MARGIN_LEFT, currentY, MARGIN_LEFT + 4f, currentY + 16f, bgPaint)

            canvas.drawText(title, MARGIN_LEFT + 10f, currentY + 13f, sectionTitlePaint)
            currentY += 22f

            strokePaint.color = Color.parseColor("#E2E8F0")
            canvas.drawLine(MARGIN_LEFT, currentY, MARGIN_RIGHT, currentY, strokePaint)
            currentY += 10f
        }

        fun drawKeyValue(label: String, value: String) {
            checkPageBreak(15f)
            val labelText = "$label: "
            val labelWidth = boldBodyPaint.measureText(labelText)

            canvas.drawText(labelText, MARGIN_LEFT, currentY, boldBodyPaint)
            if (labelWidth < CONTENT_WIDTH - 20f) {
                drawWrappedText(value, MARGIN_LEFT + labelWidth, CONTENT_WIDTH - labelWidth, bodyPaint)
            } else {
                currentY += 12f
                drawWrappedText(value, MARGIN_LEFT + 10f, CONTENT_WIDTH - 10f, bodyPaint)
            }
            currentY += 2f
        }

        // ================= PAGE 1 HEADER BANNER =================
        // Draw Banner background
        bgPaint.color = Color.parseColor("#0F172A")
        bgPaint.style = Paint.Style.FILL
        val bannerRect = RectF(MARGIN_LEFT, currentY, MARGIN_RIGHT, currentY + 70f)
        canvas.drawRoundRect(bannerRect, 8f, 8f, bgPaint)

        // Banner text
        val bannerTitlePaint = TextPaint().apply {
            color = Color.WHITE
            textSize = 18f
            typeface = Typeface.create(Typeface.DEFAULT, Typeface.BOLD)
            isAntiAlias = true
        }

        val bannerSubtitlePaint = TextPaint().apply {
            color = Color.parseColor("#93C5FD")
            textSize = 9.5f
            typeface = Typeface.create(Typeface.DEFAULT, Typeface.NORMAL)
            isAntiAlias = true
        }

        canvas.drawText(blueprint.name, MARGIN_LEFT + 14f, currentY + 28f, bannerTitlePaint)
        canvas.drawText("${blueprint.tagline} • Category: ${blueprint.category} • v${blueprint.version}", MARGIN_LEFT + 14f, currentY + 46f, bannerSubtitlePaint)

        // Health score badge
        bgPaint.color = Color.parseColor("#10B981")
        val scoreBadgeRect = RectF(MARGIN_RIGHT - 110f, currentY + 16f, MARGIN_RIGHT - 14f, currentY + 54f)
        canvas.drawRoundRect(scoreBadgeRect, 6f, 6f, bgPaint)

        val scorePaint = TextPaint().apply {
            color = Color.WHITE
            textSize = 11f
            typeface = Typeface.create(Typeface.DEFAULT, Typeface.BOLD)
            textAlign = Paint.Align.CENTER
            isAntiAlias = true
        }
        canvas.drawText("HEALTH ${blueprint.healthScore}/100", scoreBadgeRect.centerX(), scoreBadgeRect.centerY() + 4f, scorePaint)

        currentY += 82f

        // ================= SECTION 1: PRODUCT OVERVIEW =================
        drawSectionHeader("1. Executive Summary & Product Overview")
        drawKeyValue("Product Type", blueprint.ideaUnderstanding.productType)
        drawKeyValue("Target Audience", blueprint.ideaUnderstanding.targetUsers.joinToString(", "))
        drawKeyValue("Primary Problem", blueprint.ideaUnderstanding.primaryProblem)
        drawKeyValue("Proposed Solution", blueprint.ideaUnderstanding.proposedSolution)
        drawKeyValue("Business Model", blueprint.ideaUnderstanding.businessModel)

        // ================= SECTION 2: PRODUCT STRATEGY =================
        drawSectionHeader("2. Core Value Proposition & Market Strategy")
        if (blueprint.productStrategy.valueProposition.isNotBlank()) {
            drawKeyValue("Value Proposition", blueprint.productStrategy.valueProposition)
        }
        if (blueprint.productStrategy.positioning.isNotBlank()) {
            drawKeyValue("Market Positioning", blueprint.productStrategy.positioning)
        }
        if (blueprint.productStrategy.mvpScope.isNotEmpty()) {
            checkPageBreak(15f)
            canvas.drawText("MVP Core Scope:", MARGIN_LEFT, currentY, boldBodyPaint)
            currentY += 13f
            blueprint.productStrategy.mvpScope.forEach { scopeItem ->
                drawWrappedText("• $scopeItem", MARGIN_LEFT + 10f, CONTENT_WIDTH - 10f, bodyPaint)
            }
        }

        // ================= SECTION 3: TECH STACK =================
        drawSectionHeader("3. Production Tech Stack Specification")
        val stackList = listOf(
            "Frontend Client" to blueprint.techStack.frontend,
            "Backend Engine" to blueprint.techStack.backend,
            "Database Layer" to blueprint.techStack.database,
            "Authentication" to blueprint.techStack.authentication,
            "Object Storage" to blueprint.techStack.storage,
            "AI / LLM Model" to blueprint.techStack.aiModels,
            "Deployment Cloud" to blueprint.techStack.deployment
        )

        stackList.forEach { (cat, spec) ->
            drawKeyValue(cat, "${spec.name} (${spec.category}) — ${spec.justification}")
        }

        // ================= SECTION 4: FEATURE MATRIX =================
        drawSectionHeader("4. Feature Requirements & Dependency Matrix")
        blueprint.features.forEachIndexed { idx, feat ->
            checkPageBreak(25f)
            canvas.drawText("${idx + 1}. [${feat.priority}] ${feat.name}", MARGIN_LEFT, currentY, boldBodyPaint)
            currentY += 13f
            drawWrappedText("Purpose: ${feat.purpose}", MARGIN_LEFT + 10f, CONTENT_WIDTH - 10f, bodyPaint)
            if (feat.workflow.isNotBlank()) {
                drawWrappedText("Workflow: ${feat.workflow}", MARGIN_LEFT + 10f, CONTENT_WIDTH - 10f, bodyPaint)
            }
            if (feat.backendRequirements.isNotBlank()) {
                drawWrappedText("Backend Requirements: ${feat.backendRequirements}", MARGIN_LEFT + 10f, CONTENT_WIDTH - 10f, bodyPaint)
            }
            currentY += 4f
        }

        // ================= SECTION 5: SCREENS & UX =================
        drawSectionHeader("5. UI/UX Architecture & Screen Specifications")
        blueprint.uxArchitecture.screens.forEachIndexed { idx, screen ->
            checkPageBreak(25f)
            canvas.drawText("${idx + 1}. ${screen.name} (Route: ${screen.route})", MARGIN_LEFT, currentY, boldBodyPaint)
            currentY += 13f
            drawWrappedText("Description: ${screen.description}", MARGIN_LEFT + 10f, CONTENT_WIDTH - 10f, bodyPaint)
            if (screen.components.isNotEmpty()) {
                drawWrappedText("Components: ${screen.components.joinToString(", ")}", MARGIN_LEFT + 10f, CONTENT_WIDTH - 10f, bodyPaint)
            }
            currentY += 4f
        }

        // ================= SECTION 6: DATABASE SCHEMA =================
        drawSectionHeader("6. Database Schema & Entity Specifications")
        drawKeyValue("Database Engine", blueprint.databaseSchema.databaseType.uppercase())
        blueprint.databaseSchema.entities.forEach { entity ->
            checkPageBreak(30f)
            canvas.drawText("Table / Entity: ${entity.tableName}", MARGIN_LEFT, currentY, boldBodyPaint)
            currentY += 13f
            drawWrappedText("Description: ${entity.description}", MARGIN_LEFT + 10f, CONTENT_WIDTH - 10f, bodyPaint)

            // Column summary
            val fieldsSummary = entity.fields.joinToString(", ") { f ->
                "${f.name}: ${f.type}${if (f.isPrimaryKey) " [PK]" else ""}${if (f.isForeignKey) " [FK]" else ""}"
            }
            drawWrappedText("Fields: $fieldsSummary", MARGIN_LEFT + 10f, CONTENT_WIDTH - 10f, codePaint)
            currentY += 6f
        }

        // ================= SECTION 7: REST API SPECIFICATION =================
        drawSectionHeader("7. REST API Endpoints Specification")
        blueprint.apiDesign.forEach { ep ->
            checkPageBreak(25f)
            val epHeader = "${ep.method} ${ep.path} — ${ep.purpose}"
            canvas.drawText(epHeader, MARGIN_LEFT, currentY, boldBodyPaint)
            currentY += 13f
            if (ep.requestBody.isNotBlank()) {
                drawWrappedText("Request: ${ep.requestBody.take(120)}...", MARGIN_LEFT + 10f, CONTENT_WIDTH - 10f, codePaint)
            }
            if (ep.responseBody.isNotBlank()) {
                drawWrappedText("Response: ${ep.responseBody.take(120)}...", MARGIN_LEFT + 10f, CONTENT_WIDTH - 10f, codePaint)
            }
            currentY += 4f
        }

        // ================= SECTION 8: SECURITY PLAN =================
        drawSectionHeader("8. Security, Auth & Risk Mitigation")
        drawKeyValue("Authentication Strategy", blueprint.securityPlan.authenticationStrategy)
        drawKeyValue("API Key Protection", blueprint.securityPlan.apiKeyProtection)
        drawKeyValue("Rate Limiting", blueprint.securityPlan.rateLimiting)
        drawKeyValue("Encryption", blueprint.securityPlan.privacyAndEncryption)

        // ================= SECTION 9: 10-PHASE BUILD PLAN =================
        drawSectionHeader("9. 10-Phase Implementation Roadmap")
        blueprint.buildPlan.forEach { phase ->
            checkPageBreak(25f)
            canvas.drawText("Phase ${phase.phaseNumber}: ${phase.name}", MARGIN_LEFT, currentY, boldBodyPaint)
            currentY += 13f
            drawWrappedText("Target Outcome: ${phase.expectedResult}", MARGIN_LEFT + 10f, CONTENT_WIDTH - 10f, bodyPaint)
            drawWrappedText("Key Tasks: ${phase.tasks.joinToString("; ")}", MARGIN_LEFT + 10f, CONTENT_WIDTH - 10f, bodyPaint)
            currentY += 4f
        }

        // Finish last page header/footer & page
        drawHeaderFooter()
        pdfDocument.finishPage(page)

        // Save PDF file to cache directory
        val fileName = "${blueprint.name.lowercase().replace(Regex("[^a-z0-9]"), "_")}_architecture.pdf"
        val pdfFile = File(context.cacheDir, fileName)

        try {
            FileOutputStream(pdfFile).use { outputStream ->
                pdfDocument.writeTo(outputStream)
            }
            pdfDocument.close()

            // Share PDF via Intent
            val contentUri = FileProvider.getUriForFile(context, "com.example.provider", pdfFile)
            val shareIntent = Intent(Intent.ACTION_SEND).apply {
                type = "application/pdf"
                putExtra(Intent.EXTRA_STREAM, contentUri)
                putExtra(Intent.EXTRA_SUBJECT, "${blueprint.name} - Architecture Blueprint Spec")
                putExtra(Intent.EXTRA_TEXT, "Attached is the formatted software architecture specification PDF for ${blueprint.name}.")
                addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION)
            }

            context.startActivity(Intent.createChooser(shareIntent, "Save / Share Architecture PDF"))
            Toast.makeText(context, "Architecture PDF generated successfully!", Toast.LENGTH_SHORT).show()
        } catch (e: IOException) {
            e.printStackTrace()
            Toast.makeText(context, "Failed to generate PDF: ${e.localizedMessage}", Toast.LENGTH_LONG).show()
            pdfDocument.close()
        }
    }
}
